export const SET_VIEWPORT = "SET_VIEWPORT";
export const SET_ACTIVE_SECTION = "SET_ACTIVE_SECTION";
export const SET_STABLE_SECTION = "SET_STABLE_SECTION";
export const SET_IS_ENTERING = "SET_IS_ENTERING";
export const SET_COLD_ANIMATION_CANCEL_VALUE =
	"SET_COLD_ANIMATION_CANCEL_VALUE";
